spring.application.name=muncel

# puerto en el que correrá la app
server.port=8080

# 1. URL de conexión (Asegúrate de que db_mundo_celular esté creada en MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/db_mundo_celular?serverTimezone=UTC&useSSL=true&trustServerCertificate=true&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=as12
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 2. Configuración explícita de Hibernate / Dialecto (ESTO CORRIGE EL ERROR DE TU CONSOLA)
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true